# Generated by Django 3.0.7 on 2020-10-19 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_club', '0007_albumreview_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumreview',
            name='reviewedOn',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
