# Generated by Django 3.0.2 on 2020-01-26 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_group', '0002_auto_20200126_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumreview',
            name='expectations',
            field=models.CharField(choices=[('0', 'Well Below'), ('1', 'Below'), ('2', 'Slightly Below'), ('3', 'Met'), ('4', 'Slightly Above'), ('5', 'Above'), ('6', 'Well Above')], default=3, max_length=16),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('submittedOn', models.DateTimeField(auto_now=True)),
                ('on_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music_group.Album')),
                ('on_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music_group.AlbumReview')),
                ('on_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music_group.AlbumSubmission')),
                ('on_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music_group.Theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
