# Generated by Django 3.0.2 on 2020-01-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_group', '0004_auto_20200126_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumreview',
            name='expectations',
            field=models.CharField(choices=[('0', 'Well Below'), ('1', 'Below'), ('2', 'Slightly Below'), ('3', 'Met'), ('4', 'Slightly Above'), ('5', 'Above'), ('6', 'Well Above')], default='3', max_length=16),
        ),
    ]
